### ISSUE TITLE
Support for custom column types in configuration

### ISSUE THREAD

**Issue by mlavoie-sm360** [transferwise/pipelinewise-target-redshift#19]
### Describe the feature
The default column type values can be prohibitive but are very convenient to get started quickly. It would be nice to be able to provide specific column types for specific columns in `YML` config to further configure the creation of the Redshift tables.

```
...
# ------------------------------------------------------------------------------
# Source to target Schema mapping
# ------------------------------------------------------------------------------
schemas:

  - source_schema: "source"             # Source schema (aka. database) in MySQL/ MariaDB with tables
    target_schema: "target"             # Target schema in the destination Data Warehouse

    tables:
      - table_name: "a_table"
        replication_method: "FULL_TABLE"
        column_definitions:
          - column: "column_1"
             type: "VARCHAR(512)"
          - column: "column_10"
             type: "DECIMAL(2,1)"
...
```

### Who will this benefit?
This can benefit anyone using data types that do not fit the provided defaults for column types.
