### ISSUE TITLE
Allow specification of sort and dist keys

### ISSUE THREAD

**Issue by Limess** [transferwise/pipelinewise-target-redshift#39]

**Comment by koszti** [comment]
Supporting dist and sort keys makes sense. But sending it as part of the singer catalog maybe not the best option. Singer catalogs should talk only about the source databases and redshift specific parameters should be defined by this target specific options.

Another way of doing it by specifying sort and dist keys as part of the `schema_mapping` object. Schema mapping is generated automatically by using the tap catalog and the PipelineWise tap YAML files. The input YAML file would look something like this

```
...
schemas:
  - source_schema: "my_db"        # Source schema (aka. database) in MySQL/ MariaDB with tables
    target_schema: "my_db"        # Target schema in the destination Data Warehouse
    tables:
      - table_name: "table_one"
        replication_method: "LOG_BASED"   # One of INCREMENTAL, LOG_BASED and FULL_TABLE
        sort_key: column_one
        distribution_key: column_two
...    
```

If you use this target-redshift as alone and not from pipelinewise then you'd need to generate the `schema_mapping` by yourself.

What do you think? Would that work for you?
