### ISSUE TITLE
Ability for custom configurations in the COPY statement

### ISSUE THREAD

**Issue by mlavoie-sm360** [transferwise/pipelinewise-target-redshift#8]
### Describe the feature
Provide a way to customize the data format and conversion parameters of the `COPY` statement in the config file.

```
---

# ------------------------------------------------------------------------------
# General Properties
# ------------------------------------------------------------------------------
id: "redshift"                        # Unique identifier of the target
name: "Amazon Redshift"               # Name of the target
type: "target-redshift"               # !! THIS SHOULD NOT CHANGE !!


# ------------------------------------------------------------------------------
# Target - Data Warehouse connection details
# ------------------------------------------------------------------------------
db_conn:
  host: "xxxxx.redshift.amazonaws.com"          # Redshift host
  port: 5439                                    # Redshift port
  user: "<USER>"                                # Redshift user
  password: "<PASSWORD>"                        # Plain string or vault encrypted
  dbname: "<DB_NAME>"                           # Redshift database name

  # We use an intermediate S3 to load data into Redshift
  aws_access_key_id: "<ACCESS_KEY>"             # S3 - Plain string or vault encrypted
  aws_secret_access_key: "<SECRET_ACCESS_KEY>"  # S3 - Plain string or vault encrypted
  s3_bucket: "<BUCKET_NAME>"                    # S3 external bucket name
  s3_key_prefix: "redshift-imports/"            # Optional: S3 key prefix

  # COPY options
  copy_options:                                 # COPY formatting and conversion options
    - "DELIMITER ',' REMOVEQUOTES ESCAPE"
    - "BLANKSASNULL TIMEFORMAT 'auto'"
    - "COMPUPDATE OFF STATUPDATE OFF"
```

### Describe alternatives you've considered
We could fork the repo and manually modify `db_sync.py`, this seems counter productive.

We could 'fix' the `stl_load_errors` in the source data, but this is not always an available option.

### Additional context
`/target_redshift/db_sync.py` - `~ line 372`
When loading data into Redshift using the [COPY](https://docs.aws.amazon.com/redshift/latest/dg/r_COPY.html)` statement, there are a series of data format and conversion parameters that can be used. Currently, pipelinewise-target-redshift uses the following.

```
DELIMITER ',' REMOVEQUOTES ESCAPE
BLANKSASNULL TIMEFORMAT 'auto'
COMPUPDATE OFF STATUPDATE OFF
```

This is limiting if your source data requires you to use a different set of conversion parameters in order to properly execute the `COPY` statement. For example, our dataset throws a `stl_load_error` for the pipelinewise `COPY` statement but for which the following options have worked for years now. We have tested them using the CSV generated by pipelinewise and the data loads properly.

```
csv
EMPTYASNULL
TRIMBLANKS
FILLRECORD
TRUNCATECOLUMNS
GZIP
```

Different projects may require different configurations from time to time, it would be nice to provide the flexibility to customize the `COPY` statement parameters easily.

### Who will this benefit?
This would benefit every project that uses the redshift target. Assuming the default configuration works for most projects, it would require no additional configuration initially. When you do get in a project that requires further fine tuning, the option is readily available.
